SIMPLE_WORDS = ["about", "above", "across", "act", "add", "after", "again", "against", "age", "ago", "agree", "air", "all","allow", "almost", "alone", "along", "already", "also", "always", "AM", "among", "and", "anger", "angry", "animal",
"another", "answer", "any", "anyone", "anything", "anyway", "appear", "apple", "are", "area", "arm", "around", "as",
"ask", "at", "back", "bad", "bag", "ball", "band", "bank", "bar", "base", "be", "bean", "bear", "beat", "beautiful",
"bed", "before", "begin", "behind", "bell", "below", "best", "better", "between", "big", "bill", "bird", "bit",
"black", "block", "blood", "blue", "board", "boat", "body", "bomb", "bone", "book", "boom", "born", "both", "box",
"boy", "break", "bring", "brother", "brown", "build", "burn", "bus", "business", "busy", "but", "buy", "by", "call",
"can", "car", "card", "care", "carry", "case", "cat", "catch", "cause", "cell", "center", "chair", "chance",
"change", "chapter", "check", "child", "choice", "choose", "church", "city", "claim", "class", "clear", "clearly",
"close", "coach", "cold", "color", "come", "common", "community", "company", "compare", "computer", "concern",
"condition", "consider", "continue", "control", "cool", "cost", "could", "country", "couple", "course", "court",
"cover", "create", "crime", "cross", "cry", "cup", "cut", "dad", "dark", "data", "daughter", "day", "dead", "deal",
"death", "decide", "deep", "degree", "design", "desk", "die", "different", "dirt", "do", "doctor", "dog", "door",
"down", "draw", "dream", "dress", "drink", "drive", "drop", "drug", "dry", "during", "each", "early", "east", "easy",
"eat", "edge", "effect", "egg", "eight", "either", "end", "enemy", "enough", "enter", "entire", "environment", "even",
"evening", "event", "ever", "every", "everybody", "everyone", "everything", "eye", "face", "fact", "fall", "family",
"far", "farm", "fast", "father", "fear", "feel", "few", "field", "fight", "figure", "fill", "film", "final",
"finally", "find", "fine", "finger", "finish", "fire", "first", "fish", "five", "floor", "fly", "focus", "follow",
"food", "foot", "for", "force", "form", "four", "free", "friend", "from", "front", "full", "fun", "game", "garden",
"gas", "get", "girl", "give", "glass", "go", "gold", "good", "government", "great", "green", "ground", "group",
"grow", "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head", "hear",
"heart", "heat", "heavy", "help", "her", "here", "high", "him", "himself", "his", "hit", "hold", "home", "hope",
"horse", "hospital", "hot", "hotel", "hour", "house", "how", "however", "human", "hundred", "husband", "I", "idea", "if",
"image", "in", "include", "including", "increase", "indeed", "inside", "insist", "into", "is", "issue", "it", "item",
"its", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "king", "kiss", "kitchen", "know", "land",
"large", "last", "late", "later", "laugh", "law", "lead", "learn", "least", "leave", "left", "leg", "less", "let",
"letter", "level", "life", "light", "like", "line", "list", "listen", "little", "live", "local", "long", "look", "lose",
"lot", "love", "low", "machine", "main", "make", "man", "many", "map", "mark", "market", "marry", "matter", "may",
"maybe", "me", "mean", "measure", "meet", "member", "men", "might", "mile", "military", "milk", "million", "mind",
"mine", "minute", "miss", "money", "month", "more", "morning", "most", "mother", "mouth", "move", "movie", "Mr",
"Mrs", "much", "music", "must", "my", "name", "nation", "near", "neck", "need", "never", "new", "news", "next",
"nice", "night", "nine", "no", "not", "note", "nothing", "now", "number", "of", "off", "offer", "office", "often",
"oh", "oil", "ok", "old", "on", "once", "one", "only", "open", "or", "order", "other", "our", "out", "outside", "over",
"own", "page", "pain", "paint", "paper", "parent", "park", "part", "party", "pass", "past", "pay", "people", "per",
"person", "phone", "pick", "picture", "piece", "place", "plan", "plane", "plant", "play", "player", "point",
"police", "policy", "poor", "popular", "position", "possible", "power", "president", "pretty", "price", "private",
"probably", "problem", "produce", "product", "program", "prove", "provide", "pull", "push", "put", "question",
"quick", "quickly", "quiet", "quite", "race", "radio", "rain", "raise", "range", "rate", "rather", "reach", "read",
"ready", "real", "really", "reason", "receive", "recent", "red", "remain", "remember", "remove", "report", "rest",
"right", "ring", "rise", "risk", "river", "road", "rock", "role", "room", "round", "run", "safe", "same", "say",
"school", "science", "sea", "season", "seat", "second", "see", "seem", "sell", "send", "sense", "serious", "serve",
"set", "seven", "several", "sex", "shake", "shall", "she", "short", "should", "shoulder", "show", "side", "sign",
"simple", "since", "sing", "single", "sister", "sit", "six", "size", "skin", "sky", "small", "smile", "so", "social",
"soft", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sorry", "sound", "south",
"space", "speak", "special", "spend", "sport", "spring", "square", "stand", "star", "start", "state", "stay",
"step", "still", "stock", "stop", "store", "story", "street", "strong", "student", "study", "stuff", "style",
"such", "sudden", "summer", "sun", "sure", "surface", "system", "table", "take", "talk", "tall", "teach", "team",
"tell", "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", "them", "then", "there", "these",
"they", "thing", "think", "this", "those", "though", "thought", "thousand", "three",
"the", "a", "and", "is", "it", "you", "that", "he", "was", "through", "throw", "time",
"tiny", "to", "today", "together", "tonight", "too", "top", "town", "tree", "trip", "true", "try", "turn", "two",
"type", "under", "understand", "unit", "for", "on", "are", "with", "as", "I", "his", "they", "be", "at", "one", "have", "this", "from", "or", "had", "by", "not", "word", "but", "what",'unit', "until", "up", "upon", "us", "use", "usually", "very", "visit", "voice",
"wait", "walk", "wall", "want", "war", "warm", "was", "watch", "water", "way", "we", "some", "we", "can", "out", "other", "were", "all", "there", "when", "up", "use", "your", "how", "said", "an", "each",'wear', "week"]

MEDIUM_WORDS = ["abandon", "ability", "abortion", "about", "above", "abroad", "absence", "absolute", "absolutely", "confirm",
"conflict", "confront", "confusion", "Congress", "congressional", "connect", "connection", "consciousness",
"consensus", "consequence", "conservative", "considerable", "consideration", "consist", "consistent", "constant",
"constantly","absorb", "abuse", "academic", "accept", "access", "accident", "accompany", "accomplish", "according", "account", "accurate", "accuse", "achieve", "achievement", "acid", "acknowledge", "acquire", "across", "action", "active", "constitute", "constitutional", "construct", "construction", "consultant", "consume", "consumer",
"consumption", "contact", "contain", "container", "contemporary", "content", "contest", "context", "continued",
"contract", "contrast", "contribute", "activity", "actor", "actress", "actual", "actually", "ad", "adapt", "add", "addition", "additional", "address", "adequate", "adjust", "adjustment", "administration", "administrator", "admire", "admission", "admit", "", "controversial", "controversy", "convention", "conventional",
"conversation", "convert", "conviction", "convince", "cook", "cookie", "cooking", "cooperation", "cop", "cope",
"copy", "core", "corn", "corner", "corporate","adolescent", "adopt", "adult", "advance", "advanced", "advantage", "adventure", "advertising", "advice", "advise", "adviser", "advocate", "affair", "affect", "afford", "afraid", "African", "African-American", "after", "corporation", "correct", "correspondent", "cotton", "couch",
"council", "counselor", "count", "counter", "county", "courage", "cow", "crack", "craft", "crash", "crazy", "cream",
"creation", "creative", "creature", "afternoon", "again", "against", "age", "agency", "agenda", "agent", "aggressive", "ago", "agree", "agreement", "agricultural", "ah", "ahead", "aid", "aide", "AIDS", "aim", "air", "aircraft", "airline", "airport", "album", "alcohol", "alive", "all", "alliance", "allow", "ally", "almost", "alone", "along", "already",
"alter", "alternative", "amazing", "ambition", "analysis", "analyze", "ancient", "anger", "announce", "annual",
"anticipate", "anxiety", "apology", "apparent", "appeal", "appearance", "appetite", "application", "appoint",
"appreciate", "approach", "appropriate", "approval", "approve", "approximately", "architect", "area", "argument",
"arise", "arrange", "arrangement", "arrest", "arrival", "artificial", "artist", "asleep", "aspect", "assault",
"assert", "assessment", "assign", "assignment", "assist", "assistance", "associate", "association", "assume",
"assumption", "assure", "atmosphere", "attach", "attack", "attempt", "attend", "attention", "attitude", "attract",
"attractive", "auction", "audience", "author", "authority", "automatic", "available", "average", "avoid",
"awareness", "background", "balance", "barrier", "basis", "battery", "behavior", "benefit", "beside", "beyond",
"biological", "border", "borrow", "boundary", "broadcast", "budget", "burden", "calculate", "candidate", "capacity",
"capital", "capture", "career", "careful", "carefully", "category", "celebrate", "celebration", "cell", "ceremony",
"challenge", "champion", "channel", "character", "characteristic", "charity", "chemical", "circumstance",
"citizen", "civil", "civilization", "classic", "climate", "collapse", "colleague", "collect", "collection",
"college", "combine", "comfortable", "command", "comment", "commercial", "commission", "commit", "committee",
"communication", "community", "compare", "comparison", "compete", "competition", "competitive", "complaint",
"complex", "complicated", "component", "comprehensive", "compromise", "concern", "conclude", "conclusion",
"concrete", "condition", "conduct", "conference", "confidence", "confident", "confirm", "conflict", "conscious",
"consequence", "considerable", "consist", "constant", "construct", "consult", "consume", "contact", "contain",
"contemporary", "content", "contest", "context", "continue", "contract", "contrast", "contribute", "control",
"convenient", "conversation", "convince", "cooperation", "corporate", "correspond", "counsel", "counter",
"creative", "credit", "crisis", "criteria", "critic", "criticism", "crucial", "currency", "current", "cycle",
"debate", "decade", "declare", "decline", "decrease", "dedicate", "defeat", "defend", "define", "definition",
"degree", "delay", "democracy", "demonstrate", "density", "depend", "depression", "depth", "describe", "description",
"desert", "design", "desire", "desperate", "despite", "destroy", "destruction", "detail", "detect", "determine",
"develop", "development", "device", "devote", "diagnosis", "dialogue", "difference", "different", "difficult",
"difficulty", "dimension", "direction", "director", "disaster", "discipline", "discuss", "discussion", "disease",
"disorder", "display", "dispute", "distance", "distinct", "distinguish", "distribute", "distribution", "district",
"diverse", "diversity", "divide", "division", "dominate", "dramatic", "duration", "economy", "edition", "educate",
"education", "effect", "effective", "efficiency", "efficient", "effort", "elaborate", "election", "electric",
"element", "eliminate", "emerge", "emergency", "emphasis", "emphasize", "employee", "employer", "encounter",
"encourage", "energy", "engage", "engine", "enhance", "enormous", "ensure", "environment", "equation", "equipment",
"equivalent", "error", "escape", "especially", "essential", "establish", "estimate", "ethnic", "evaluate", "event",
"eventually", "evidence", "evolution", "exact", "examine", "example", "exchange", "exclude", "execute",
"executive", "exhibit", "exist", "existence", "expansion", "expect", "expectation", "expense", "experiment",
"expert", "explain", "explanation", "explore", "explosion", "export", "expose", "expression", "extend",
"extension", "extent", "external", "extraordinary", "extreme", "facility", "factor", "faculty", "failure", "faith",
"familiar", "family", "fantasy", "fashion", "feature", "federal", "feedback", "female", "festival", "fiction",
"finance", "financial", "focus", "following", "force", "foreign", "forest", "forever", "formal", "formation",
"former", "fortune", "foundation", "fragment", "framework", "frequent", "frequently", "frustrate", "function",
"fundamental", "furniture", "further", "future", "generate", "generation", "generous", "genetic", "genuine",
"gesture", "global", "govern", "government", "governor", "gradual", "graduate", "guarantee", "habit", "handful",
"handle", "happen", "hardly", "headline", "health", "healthy", "hearing", "heavily", "height", "heritage",
"highlight", "historic", "honest", "horizon", "horror", "hospital", "household", "housing", "however", "human",
"humor", "hypothesis", "identity", "ignore", "illegal", "illness", "illustrate", "image", "imagination",
"immediately", "immigrant", "immigration", "impact", "implement", "implication", "imply", "important",
"impose", "impossible", "impress", "impression", "improve", "improvement", "incident", "income", "incorporate",
"independent", "index", "indicate", "indication", "individual", "industrial", "industry", "inevitable",
"influence", "inform", "information", "initial", "initiative", "injury", "innocent", "inquiry", "insight",
"instance", "institute", "institution", "instruction", "instructor", "instrument", "insurance", "integrate",
"intellectual", "intelligence", "intend", "intense", "intention", "interaction", "interest", "internal",
"interpret", "interpretation", "interrupt", "interval", "interview", "introduce", "investment", "investor",
"invitation", "involve", "isolate", "issue", "journal", "journey", "judge", "judgment", "justice", "justify",
"knowledge", "labor", "landscape", "language", "largely", "launch", "lawyer", "layer", "leadership",
"learning", "lecture", "legal", "legend", "legislation", "liability", "liberal", "library", "license",
"lifestyle", "lifetime", "literature", "location", "logical", "loyal", "luxury", "magazine", "maintenance",
"majority", "manufacturer", "margin", "marriage", "material", "meaning", "mechanism", "media", "medicine",
"medium", "memory", "mental", "mention", "method", "military", "minority", "mobile", "moderate", "modify",
"monitor", "motivation", "mountain", "movement", "multiple", "murder", "muscle", "museum", "mystery",
"narrative", "nation", "national", "native", "natural", "nature", "necessary", "negative", "neglect", "negotiate",
"network", "neutral", "newspaper", "nightmare", "nomination", "normal", "normally", "notion", "novel", "nuclear",
"objective", "obligation", "observation", "observe", "obtain", "obvious", "occasion", "occupy", "occur",
"offense", "offensive", "official", "operate", "operation", "opinion", "opponent", "opportunity",

"oppose",
"opposite", "opposition", "option", "ordinary", "organic", "organization", "origin", "original", "otherwise",
"outcome", "output", "outstanding", "overall", "overcome", "overlook", "participate", "participation",
"particular", "partly", "partner", "partnership", "passage", "passenger", "passion", "passive", "password",
"patient", "pattern", "payment", "perceive", "percentage", "perception", "performance", "permanent",
"permission", "permit", "personality", "perspective", "persuade", "phenomenon", "philosophy", "physical",
"physician", "pipeline", "planning", "platform", "pleasure", "plenty", "politician", "politics", "portion",
"portrait", "position", "positive", "possess", "possession", "potential", "poverty", "practical", "practice",
"precise", "predict", "preference", "preparation", "presence", "preserve", "president", "pressure",
"previous", "primary", "principal", "principle", "priority", "privacy", "private", "probability", "problem",
"procedure", "process", "produce", "producer", "product", "production", "professional", "profit",
"progress", "project", "promise", "promotion", "proof", "property", "proportion", "proposal", "propose",
"prospect", "protect", "protection", "protest", "protocol", "psychology", "publication", "publicity",
"purchase", "pursue", "quantity", "quarter", "question", "racial", "radical", "radio", "random", "range",
"rapid", "rarely", "rating", "ratio", "reaction", "reading", "reality", "realize", "reason", "reasonable",
"rebuild", "recall", "receive", "recent", "reception", "recommend", "recommendation", "recover",
"recovery", "recruit", "reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform",
"refuse", "regard", "regional", "register", "regulate", "regulation", "reinforce", "reject", "relate",
"relation", "relationship", "relative", "relatively", "relax", "release", "relevant", "reliability",
"reliable", "relief", "religion", "remark", "remarkable", "remember", "remind", "remote", "removal",
"render", "renew", "repair", "repeat", "replace", "reply", "report", "reporter", "represent",
"representation", "representative", "reputation", "require", "requirement", "research", "researcher",
"resemble", "reserve", "residence", "resident", "resist", "resistance", "resolution", "resolve",
"respect", "respond", "response", "responsibility", "responsible", "restaurant", "restore", "restriction",
"result", "retain", "retirement", "reveal", "revenue", "reverse", "review", "revolution", "rhythm",
"ritual", "romantic", "roughly", "routine", "royal", "rubber", "sacrifice", "safety", "salary",
"sample", "satisfaction", "satisfactory", "satisfy", "scale", "schedule", "scholar", "scholarship",
"scope", "secretary", "section", "sector", "security", "sensation", "sensitive", "sentence",
"separate", "sequence", "series", "serious", "session", "setting", "settlement", "severe", "sexual",
"shadow", "shape", "shareholder", "shelter", "shift", "significance", "significant", "silence",
"similar", "similarly", "simple", "simply", "sincere", "singular", "situation", "skeptical", "slightly",
"smooth", "social", "society", "software", "solid", "solution", "solve", "somehow", "sophisticated",
"southern", "species", "specific", "specifically", "specify", "speculation", "sphere", "spiritual",
"spokesman", "sponsor", "spread", "stable", "statement", "statistics", "status", "steady",
"stereotype", "stimulate", "straightforward", "strategy", "strength", "stress", "stretch",
"structural", "structure", "struggle", "stumble", "subsequent", "subsequently", "substance",
"substantial", "succeed", "success", "successful", "succession", "suddenly", "sufficient",
"suggest", "suggestion", "suitcase", "summarize", "summary", "supplement", "supply", "support",
"suppose", "supposed", "suppress", "surely", "surface", "surgery", "surplus", "surround",
"survival", "survive", "suspect", "suspicion", "sustain", "sustainable", "symbol", "sympathy",
"systematic", "tactic", "tendency", "tension", "territory", "testimony", "theater", "thesis",
"thorough", "thought", "threat", "threaten", "throughout", "thus", "tissue", "tolerance",
"tolerate", "total", "tough", "trace", "tradition", "traditional", "traffic", "transfer",
"transform", "transition", "translate", "translation", "transport", "treatment", "trend",
"trial", "triumph", "tropical", "typical", "ultimate", "unanimous", "uncertain", "undergo",
"undermine", "understand", "understanding", "undertake", "uniform", "unique", "unite",
"universal", "university", "unknown", "unlike", "unlikely", "until", "unusual", "upgrade",
"upward", "urban", "urge", "urgent", "utility", "utilize", "vacation", "valid", "valuable",
"variable", "variation", "variety", "various", "vehicle", "venture", "version", "vertical",
"victory", "violence", "virtually", "virtue", "visible", "vision", "visual", "vital",
"voluntary", "volunteer", "vulnerable", "wage", "wait", "wander", "warmth", "weakness",
"wealth", "weapon", "weather", "website", "wedding", "weekend", "weird", "welcome",
"welfare", "western", "whereas", "wherever", "whether", "widespread", "willing",
"withdraw", "witness", "wonderful", "workforce", "workshop", "worldwide",
"worth", "worthy", "writing", "yield", "young", "youth", "zone"




]


HARD_WORDS = [
    "alleviate", "ambiguous", "anecdote", "analyze", "antagonize", "apathy", "arbitrary", "assess", "assert", "assimilate",
    "audacious", "augment", "authentic", "bias", "brevity", "bureaucratic", "candid", "coherent", "collaborate", "comprehensive",
    "concede", "concurrent", "condone", "consequently", "contradict", "corroborate", "credible", "critique", "culminate", "cynical",
    "debate", "deduce", "deficit", "delineate", "denounce", "depict", "deteriorate", "deviate", "discrepancy", "disseminate",
    "distort", "diverse", "dominate", "elaborate", "elicit", "empirical", "endeavor", "enhance", "eradicate", "evaluate",
    "exacerbate", "exemplify", "exhaustive", "feasible", "fluctuate", "formidable", "frivolous", "fundamental", "hierarchy", "hypothesis",
    "illustrate", "immense", "imminent", "impartial", "implement", "imply", "incentive", "incline", "inconsistent", "indifferent",
    "inevitable", "infer", "integral", "intensify", "intervene", "intuitive", "intricate", "invariably", "ironic", "justify",
    "lucrative", "manipulate", "meticulous", "negligible", "notion", "obstacle", "offset", "paradox", "perceive", "pertinent",
    "plausible", "predominant", "prevalent", "profound", "prohibit", "propensity", "proponent", "rational", "reciprocal", "redundant",
    "relevant", "resilient", "restrain", "retrospect", "reveal", "rigorous", "scrutiny", "subsequent", "substantial", "succinct",
    "superficial", "sustain", "tangible", "tentative", "theoretical", "undermine", "unprecedented", "validate", "viable", "volatile",
    "abate", "aberration", "abhor", "abstain", "abstract", "abundant", "acclaim", "acumen", "adept", "adverse",
    "advocate", "aesthetic", "affluent", "agile", "alienate", "allocate", "ambivalent", "anachronistic", "analyze", "animosity",
    "anomaly", "anonymous", "antagonist", "anticipate", "antipathy", "apprehensive", "arbitrary", "arduous", "articulate", "assert",
    "assess", "assiduous", "assimilate", "astute", "atrocity", "attain", "attribute", "audacious", "augment", "austere",
    "authentic", "autonomous", "aversion", "belligerent", "benevolent", "biased", "bolster", "brevity", "candid", "capricious",
    "catalyst", "caustic", "censure", "circuitous", "circumvent", "clandestine", "coerce", "cognitive", "coherent", "cohesive",
    "collaborate", "colloquial", "commence", "compelling", "complacent", "comprehensive", "conceive", "concise", "concurrent", "condone",
    "conform", "congregate", "consensus", "consequently", "consolidate", "conspicuous", "constrain", "constructive", "contemplate", "contentious",
    "contingent", "contradict", "contribute", "conundrum", "conventional", "converge", "convey", "conviction", "corroborate", "counteract",
    "credibility", "culminate", "cynical", "debate", "decipher", "deficiency", "deficit", "delineate", "demise", "denounce",
    "depict", "derive", "detrimental", "deviation", "dichotomy", "diffuse", "diminish", "discern", "discrepancy", "discriminate",
    "disdain", "disparage", "disparate", "dispel", "disseminate", "dissipate", "distort", "divergent", "divulge", "dogmatic",
    "dominate", "dynamic", "eclectic", "elaborate", "elicit", "elude", "emulate", "endeavor", "enhance", "enigma",
    "ephemeral", "equitable", "erratic", "esoteric", "establish", "evade", "evaluate", "evoke", "exacerbate", "exemplary",
    "exhaustive", "exonerate", "expedite", "exploit", "facilitate", "feasible", "fluctuate", "forage", "formidable", "fortify",
    "foster", "frivolous", "fundamental", "galvanize", "garner", "gregarious", "hamper", "hierarchy", "hypothetical", "idiosyncratic",
    "illuminate", "illustrate", "immerse", "immense", "imminent", "impartial", "implement", "implicit", "incentive", "incessant",
    "inclination", "incompetent", "inconsistent", "indifferent", "indigenous", "induce", "inevitable", "infer", "inherent", "innovate",
    "insatiable", "insight", "insinuate", "integral", "integrate", "intensify", "intermittent", "intricate", "inundate", "invalidate",
    "invoke", "ironic", "jargon", "juxtapose", "keen", "latent", "laud", "legitimate", "lethargic", "lucid",
    "lucrative", "malicious", "manifest", "manipulate", "marginal", "melancholy", "meticulous", "mitigate", "mundane", "negligent",
    "notion", "novel", "nuance", "oblivious", "obsolete", "obstinate", "obstruct", "ominous", "onerous", "opaque",
    "oppress", "optimistic", "ornate", "paradox", "paramount", "partisan", "patronize", "perception", "perennial", "peril",
    "permeate", "perpetuate", "pervasive", "plausible", "ponder", "potent", "pragmatic", "precedent", "predominant", "preliminary",
    "prevalent", "profound", "prohibit", "propensity", "proponent", "provisional", "prudent", "qualitative", "quantitative", "quintessential",
    "ramification", "rationale", "rebuke", "reciprocal", "refine", "reiterate", "relinquish", "relevant", "remorse", "renowned",
    "repercussion", "resilient", "restrain", "retaliate", "revere", "rigorous", "rudimentary", "scrutinize", "secular", "simultaneous",
    "skeptical", "solicit", "speculate", "spontaneous", "sporadic", "staunch", "stringent", "subsequent", "substantiate", "subtle",
    "succinct", "superficial", "suppress", "surpass", "sustain", "tangible", "tentative", "terse", "theoretical", "transcend",
    "transparent", "turbulent", "ubiquitous", "unprecedented", "validate", "vehement", "venerate", "veracity", "vicarious", "vigilant",
    "vindicate", "volatile", "warrant", "whimsical", "widespread", "witty", "yield", "zealous"




]

def get_words(difficulty):
    if difficulty == "simple":
        return SIMPLE_WORDS
    elif difficulty == "medium":
        return MEDIUM_WORDS
    elif difficulty == "hard":
        return HARD_WORDS
    else:
        raise ValueError("Invalid difficulty level")