import random

# SIMPLE_WORDS = [
#     "cat", "dog", "house", "tree", "book", "sun", "moon", "fish", "bird", "car",
#     "apple", "ball", "chair", "door", "egg", "flower", "grass", "hat", "ice", "juice",
#     "kite", "lamp", "milk", "nest", "orange", "pen", "queen", "rain", "star", "table"
# ]



    
SIMPLE_WORDS = ["about", "above", "across", "act", "add", "after", "again", "against", "age", "ago", "agree", "air", "all","allow", "almost", "alone", "along", "already", "also", "always", "AM", "among", "and", "anger", "angry", "animal",
"another", "answer", "any", "anyone", "anything", "anyway", "appear", "apple", "are", "area", "arm", "around", "as",
"ask", "at", "back", "bad", "bag", "ball", "band", "bank", "bar", "base", "be", "bean", "bear", "beat", "beautiful",
"bed", "before", "begin", "behind", "bell", "below", "best", "better", "between", "big", "bill", "bird", "bit",
"black", "block", "blood", "blue", "board", "boat", "body", "bomb", "bone", "book", "boom", "born", "both", "box",
"boy", "break", "bring", "brother", "brown", "build", "burn", "bus", "business", "busy", "but", "buy", "by", "call",
"can", "car", "card", "care", "carry", "case", "cat", "catch", "cause", "cell", "center", "chair", "chance",
"change", "chapter", "check", "child", "choice", "choose", "church", "city", "claim", "class", "clear", "clearly",
"close", "coach", "cold", "color", "come", "common", "community", "company", "compare", "computer", "concern",
"condition", "consider", "continue", "control", "cool", "cost", "could", "country", "couple", "course", "court",
"cover", "create", "crime", "cross", "cry", "cup", "cut", "dad", "dark", "data", "daughter", "day", "dead", "deal",
"death", "decide", "deep", "degree", "design", "desk", "die", "different", "dirt", "do", "doctor", "dog", "door",
"down", "draw", "dream", "dress", "drink", "drive", "drop", "drug", "dry", "during", "each", "early", "east", "easy",
"eat", "edge", "effect", "egg", "eight", "either", "end", "enemy", "enough", "enter", "entire", "environment", "even",
"evening", "event", "ever", "every", "everybody", "everyone", "everything", "eye", "face", "fact", "fall", "family",
"far", "farm", "fast", "father", "fear", "feel", "few", "field", "fight", "figure", "fill", "film", "final",
"finally", "find", "fine", "finger", "finish", "fire", "first", "fish", "five", "floor", "fly", "focus", "follow",
"food", "foot", "for", "force", "form", "four", "free", "friend", "from", "front", "full", "fun", "game", "garden",
"gas", "get", "girl", "give", "glass", "go", "gold", "good", "government", "great", "green", "ground", "group",
"grow", "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head", "hear",
"heart", "heat", "heavy", "help", "her", "here", "high", "him", "himself", "his", "hit", "hold", "home", "hope",
"horse", "hospital", "hot", "hotel", "hour", "house", "how", "however", "human", "hundred", "husband", "I", "idea", "if",
"image", "in", "include", "including", "increase", "indeed", "inside", "insist", "into", "is", "issue", "it", "item",
"its", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "king", "kiss", "kitchen", "know", "land",
"large", "last", "late", "later", "laugh", "law", "lead", "learn", "least", "leave", "left", "leg", "less", "let",
"letter", "level", "life", "light", "like", "line", "list", "listen", "little", "live", "local", "long", "look", "lose",
"lot", "love", "low", "machine", "main", "make", "man", "many", "map", "mark", "market", "marry", "matter", "may",
"maybe", "me", "mean", "measure", "meet", "member", "men", "might", "mile", "military", "milk", "million", "mind",
"mine", "minute", "miss", "money", "month", "more", "morning", "most", "mother", "mouth", "move", "movie", "Mr",
"Mrs", "much", "music", "must", "my", "name", "nation", "near", "neck", "need", "never", "new", "news", "next",
"nice", "night", "nine", "no", "not", "note", "nothing", "now", "number", "of", "off", "offer", "office", "often",
"oh", "oil", "ok", "old", "on", "once", "one", "only", "open", "or", "order", "other", "our", "out", "outside", "over",
"own", "page", "pain", "paint", "paper", "parent", "park", "part", "party", "pass", "past", "pay", "people", "per",
"person", "phone", "pick", "picture", "piece", "place", "plan", "plane", "plant", "play", "player", "point",
"police", "policy", "poor", "popular", "position", "possible", "power", "president", "pretty", "price", "private",
"probably", "problem", "produce", "product", "program", "prove", "provide", "pull", "push", "put", "question",
"quick", "quickly", "quiet", "quite", "race", "radio", "rain", "raise", "range", "rate", "rather", "reach", "read",
"ready", "real", "really", "reason", "receive", "recent", "red", "remain", "remember", "remove", "report", "rest",
"right", "ring", "rise", "risk", "river", "road", "rock", "role", "room", "round", "run", "safe", "same", "say",
"school", "science", "sea", "season", "seat", "second", "see", "seem", "sell", "send", "sense", "serious", "serve",
"set", "seven", "several", "sex", "shake", "shall", "she", "short", "should", "shoulder", "show", "side", "sign",
"simple", "since", "sing", "single", "sister", "sit", "six", "size", "skin", "sky", "small", "smile", "so", "social",
"soft", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sorry", "sound", "south",
"space", "speak", "special", "spend", "sport", "spring", "square", "stand", "star", "start", "state", "stay",
"step", "still", "stock", "stop", "store", "story", "street", "strong", "student", "study", "stuff", "style",
"such", "sudden", "summer", "sun", "sure", "surface", "system", "table", "take", "talk", "tall", "teach", "team",
"tell", "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", "them", "then", "there", "these",
"they", "thing", "think", "this", "those", "though", "thought", "thousand", "three",
"the", "a", "and", "is", "it", "you", "that", "he", "was", "through", "throw", "time",
"tiny", "to", "today", "together", "tonight", "too", "top", "town", "tree", "trip", "true", "try", "turn", "two",
"type", "under", "understand", "unit", "for", "on", "are", "with", "as", "I", "his", "they", "be", "at", "one", "have", "this", "from", "or", "had", "by", "not", "word", "but", "what",'unit', "until", "up", "upon", "us", "use", "usually", "very", "visit", "voice",
"wait", "walk", "wall", "want", "war", "warm", "was", "watch", "water", "way", "we", "some", "we", "can", "out", "other", "were", "all", "there", "when", "up", "use", "your", "how", "said", "an", "each",'wear', "week"]



# MEDIUM_WORDS = [
#     "beautiful", "computer", "elephant", "umbrella", "chocolate", "butterfly", "telephone", "mountain", "restaurant", "adventure",
#     "calendar", "daughter", "exercise", "furniture", "geography", "happiness", "imagination", "knowledge", "language", "medicine",
#     "neighbor", "orchestra", "photograph", "question", "remember", "schedule", "temperature", "understand", "vacation", "wonderful"
# ]


MEDIUM_WORDS = ["abandon", "ability", "abortion", "about", "above", "abroad", "absence", "absolute", "absolutely", "confirm",
"conflict", "confront", "confusion", "Congress", "congressional", "connect", "connection", "consciousness",
"consensus", "consequence", "conservative", "considerable", "consideration", "consist", "consistent", "constant",
"constantly","absorb", "abuse", "academic", "accept", "access", "accident", "accompany", "accomplish", "according", "account", "accurate", "accuse", "achieve", "achievement", "acid", "acknowledge", "acquire", "across", "action", "active", "constitute", "constitutional", "construct", "construction", "consultant", "consume", "consumer",
"consumption", "contact", "contain", "container", "contemporary", "content", "contest", "context", "continued",
"contract", "contrast", "contribute", "activity", "actor", "actress", "actual", "actually", "ad", "adapt", "add", "addition", "additional", "address", "adequate", "adjust", "adjustment", "administration", "administrator", "admire", "admission", "admit", "", "controversial", "controversy", "convention", "conventional",
"conversation", "convert", "conviction", "convince", "cook", "cookie", "cooking", "cooperation", "cop", "cope",
"copy", "core", "corn", "corner", "corporate","adolescent", "adopt", "adult", "advance", "advanced", "advantage", "adventure", "advertising", "advice", "advise", "adviser", "advocate", "affair", "affect", "afford", "afraid", "African", "African-American", "after", "corporation", "correct", "correspondent", "cotton", "couch",
"council", "counselor", "count", "counter", "county", "courage", "cow", "crack", "craft", "crash", "crazy", "cream",
"creation", "creative", "creature", "afternoon", "again", "against", "age", "agency", "agenda", "agent", "aggressive", "ago", "agree", "agreement", "agricultural", "ah", "ahead", "aid", "aide", "AIDS", "aim", "air", "aircraft", "airline", "airport", "album", "alcohol", "alive", "all", "alliance", "allow", "ally", "almost", "alone", "along", "already",
"alter", "alternative", "amazing", "ambition", "analysis", "analyze", "ancient", "anger", "announce", "annual",
"anticipate", "anxiety", "apology", "apparent", "appeal", "appearance", "appetite", "application", "appoint",
"appreciate", "approach", "appropriate", "approval", "approve", "approximately", "architect", "area", "argument",
"arise", "arrange", "arrangement", "arrest", "arrival", "artificial", "artist", "asleep", "aspect", "assault",
"assert", "assessment", "assign", "assignment", "assist", "assistance", "associate", "association", "assume",
"assumption", "assure", "atmosphere", "attach", "attack", "attempt", "attend", "attention", "attitude", "attract",
"attractive", "auction", "audience", "author", "authority", "automatic", "available", "average", "avoid",
"awareness", "background", "balance", "barrier", "basis", "battery", "behavior", "benefit", "beside", "beyond",
"biological", "border", "borrow", "boundary", "broadcast", "budget", "burden", "calculate", "candidate", "capacity",
"capital", "capture", "career", "careful", "carefully", "category", "celebrate", "celebration", "cell", "ceremony",
"challenge", "champion", "channel", "character", "characteristic", "charity", "chemical", "circumstance",
"citizen", "civil", "civilization", "classic", "climate", "collapse", "colleague", "collect", "collection",
"college", "combine", "comfortable", "command", "comment", "commercial", "commission", "commit", "committee",
"communication", "community", "compare", "comparison", "compete", "competition", "competitive", "complaint",
"complex", "complicated", "component", "comprehensive", "compromise", "concern", "conclude", "conclusion",
"concrete", "condition", "conduct", "conference", "confidence", "confident", "confirm", "conflict", "conscious",
"consequence", "considerable", "consist", "constant", "construct", "consult", "consume", "contact", "contain",
"contemporary", "content", "contest", "context", "continue", "contract", "contrast", "contribute", "control",
"convenient", "conversation", "convince", "cooperation", "corporate", "correspond", "counsel", "counter",
"creative", "credit", "crisis", "criteria", "critic", "criticism", "crucial", "currency", "current", "cycle",
"debate", "decade", "declare", "decline", "decrease", "dedicate", "defeat", "defend", "define", "definition",
"degree", "delay", "democracy", "demonstrate", "density", "depend", "depression", "depth", "describe", "description",
"desert", "design", "desire", "desperate", "despite", "destroy", "destruction", "detail", "detect", "determine",
"develop", "development", "device", "devote", "diagnosis", "dialogue", "difference", "different", "difficult",
"difficulty", "dimension", "direction", "director", "disaster", "discipline", "discuss", "discussion", "disease",
"disorder", "display", "dispute", "distance", "distinct", "distinguish", "distribute", "distribution", "district",
"diverse", "diversity", "divide", "division", "dominate", "dramatic", "duration", "economy", "edition", "educate",
"education", "effect", "effective", "efficiency", "efficient", "effort", "elaborate", "election", "electric",
"element", "eliminate", "emerge", "emergency", "emphasis", "emphasize", "employee", "employer", "encounter",
"encourage", "energy", "engage", "engine", "enhance", "enormous", "ensure", "environment", "equation", "equipment",
"equivalent", "error", "escape", "especially", "essential", "establish", "estimate", "ethnic", "evaluate", "event",
"eventually", "evidence", "evolution", "exact", "examine", "example", "exchange", "exclude", "execute",
"executive", "exhibit", "exist", "existence", "expansion", "expect", "expectation", "expense", "experiment",
"expert", "explain", "explanation", "explore", "explosion", "export", "expose", "expression", "extend",
"extension", "extent", "external", "extraordinary", "extreme", "facility", "factor", "faculty", "failure", "faith",
"familiar", "family", "fantasy", "fashion", "feature", "federal", "feedback", "female", "festival", "fiction",
"finance", "financial", "focus", "following", "force", "foreign", "forest", "forever", "formal", "formation",
"former", "fortune", "foundation", "fragment", "framework", "frequent", "frequently", "frustrate", "function",
"fundamental", "furniture", "further", "future", "generate", "generation", "generous", "genetic", "genuine",
"gesture", "global", "govern", "government", "governor", "gradual", "graduate", "guarantee", "habit", "handful",
"handle", "happen", "hardly", "headline", "health", "healthy", "hearing", "heavily", "height", "heritage",
"highlight", "historic", "honest", "horizon", "horror", "hospital", "household", "housing", "however", "human",
"humor", "hypothesis", "identity", "ignore", "illegal", "illness", "illustrate", "image", "imagination",
"immediately", "immigrant", "immigration", "impact", "implement", "implication", "imply", "important",
"impose", "impossible", "impress", "impression", "improve", "improvement", "incident", "income", "incorporate",
"independent", "index", "indicate", "indication", "individual", "industrial", "industry", "inevitable",
"influence", "inform", "information", "initial", "initiative", "injury", "innocent", "inquiry", "insight",
"instance", "institute", "institution", "instruction", "instructor", "instrument", "insurance", "integrate",
"intellectual", "intelligence", "intend", "intense", "intention", "interaction", "interest", "internal",
"interpret", "interpretation", "interrupt", "interval", "interview", "introduce", "investment", "investor",
"invitation", "involve", "isolate", "issue", "journal", "journey", "judge", "judgment", "justice", "justify",
"knowledge", "labor", "landscape", "language", "largely", "launch", "lawyer", "layer", "leadership",
"learning", "lecture", "legal", "legend", "legislation", "liability", "liberal", "library", "license",
"lifestyle", "lifetime", "literature", "location", "logical", "loyal", "luxury", "magazine", "maintenance",
"majority", "manufacturer", "margin", "marriage", "material", "meaning", "mechanism", "media", "medicine",
"medium", "memory", "mental", "mention", "method", "military", "minority", "mobile", "moderate", "modify",
"monitor", "motivation", "mountain", "movement", "multiple", "murder", "muscle", "museum", "mystery",
"narrative", "nation", "national", "native", "natural", "nature", "necessary", "negative", "neglect", "negotiate",
"network", "neutral", "newspaper", "nightmare", "nomination", "normal", "normally", "notion", "novel", "nuclear",
"objective", "obligation", "observation", "observe", "obtain", "obvious", "occasion", "occupy", "occur",
"offense", "offensive", "official", "operate", "operation", "opinion", "opponent", "opportunity",

"oppose",
"opposite", "opposition", "option", "ordinary", "organic", "organization", "origin", "original", "otherwise",
"outcome", "output", "outstanding", "overall", "overcome", "overlook", "participate", "participation",
"particular", "partly", "partner", "partnership", "passage", "passenger", "passion", "passive", "password",
"patient", "pattern", "payment", "perceive", "percentage", "perception", "performance", "permanent",
"permission", "permit", "personality", "perspective", "persuade", "phenomenon", "philosophy", "physical",
"physician", "pipeline", "planning", "platform", "pleasure", "plenty", "politician", "politics", "portion",
"portrait", "position", "positive", "possess", "possession", "potential", "poverty", "practical", "practice",
"precise", "predict", "preference", "preparation", "presence", "preserve", "president", "pressure",
"previous", "primary", "principal", "principle", "priority", "privacy", "private", "probability", "problem",
"procedure", "process", "produce", "producer", "product", "production", "professional", "profit",
"progress", "project", "promise", "promotion", "proof", "property", "proportion", "proposal", "propose",
"prospect", "protect", "protection", "protest", "protocol", "psychology", "publication", "publicity",
"purchase", "pursue", "quantity", "quarter", "question", "racial", "radical", "radio", "random", "range",
"rapid", "rarely", "rating", "ratio", "reaction", "reading", "reality", "realize", "reason", "reasonable",
"rebuild", "recall", "receive", "recent", "reception", "recommend", "recommendation", "recover",
"recovery", "recruit", "reduce", "reduction", "refer", "reference", "reflect", "reflection", "reform",
"refuse", "regard", "regional", "register", "regulate", "regulation", "reinforce", "reject", "relate",
"relation", "relationship", "relative", "relatively", "relax", "release", "relevant", "reliability",
"reliable", "relief", "religion", "remark", "remarkable", "remember", "remind", "remote", "removal",
"render", "renew", "repair", "repeat", "replace", "reply", "report", "reporter", "represent",
"representation", "representative", "reputation", "require", "requirement", "research", "researcher",
"resemble", "reserve", "residence", "resident", "resist", "resistance", "resolution", "resolve",
"respect", "respond", "response", "responsibility", "responsible", "restaurant", "restore", "restriction",
"result", "retain", "retirement", "reveal", "revenue", "reverse", "review", "revolution", "rhythm",
"ritual", "romantic", "roughly", "routine", "royal", "rubber", "sacrifice", "safety", "salary",
"sample", "satisfaction", "satisfactory", "satisfy", "scale", "schedule", "scholar", "scholarship",
"scope", "secretary", "section", "sector", "security", "sensation", "sensitive", "sentence",
"separate", "sequence", "series", "serious", "session", "setting", "settlement", "severe", "sexual",
"shadow", "shape", "shareholder", "shelter", "shift", "significance", "significant", "silence",
"similar", "similarly", "simple", "simply", "sincere", "singular", "situation", "skeptical", "slightly",
"smooth", "social", "society", "software", "solid", "solution", "solve", "somehow", "sophisticated",
"southern", "species", "specific", "specifically", "specify", "speculation", "sphere", "spiritual",
"spokesman", "sponsor", "spread", "stable", "statement", "statistics", "status", "steady",
"stereotype", "stimulate", "straightforward", "strategy", "strength", "stress", "stretch",
"structural", "structure", "struggle", "stumble", "subsequent", "subsequently", "substance",
"substantial", "succeed", "success", "successful", "succession", "suddenly", "sufficient",
"suggest", "suggestion", "suitcase", "summarize", "summary", "supplement", "supply", "support",
"suppose", "supposed", "suppress", "surely", "surface", "surgery", "surplus", "surround",
"survival", "survive", "suspect", "suspicion", "sustain", "sustainable", "symbol", "sympathy",
"systematic", "tactic", "tendency", "tension", "territory", "testimony", "theater", "thesis",
"thorough", "thought", "threat", "threaten", "throughout", "thus", "tissue", "tolerance",
"tolerate", "total", "tough", "trace", "tradition", "traditional", "traffic", "transfer",
"transform", "transition", "translate", "translation", "transport", "treatment", "trend",
"trial", "triumph", "tropical", "typical", "ultimate", "unanimous", "uncertain", "undergo",
"undermine", "understand", "understanding", "undertake", "uniform", "unique", "unite",
"universal", "university", "unknown", "unlike", "unlikely", "until", "unusual", "upgrade",
"upward", "urban", "urge", "urgent", "utility", "utilize", "vacation", "valid", "valuable",
"variable", "variation", "variety", "various", "vehicle", "venture", "version", "vertical",
"victory", "violence", "virtually", "virtue", "visible", "vision", "visual", "vital",
"voluntary", "volunteer", "vulnerable", "wage", "wait", "wander", "warmth", "weakness",
"wealth", "weapon", "weather", "website", "wedding", "weekend", "weird", "welcome",
"welfare", "western", "whereas", "wherever", "whether", "widespread", "willing",
"withdraw", "witness", "wonderful", "workforce", "workshop", "worldwide",
"worth", "worthy", "writing", "yield", "young", "youth", "zone"




]


# HARD_WORDS = [
#     "conscientious", "phenomenon", "enthusiasm", "sophisticated", "perseverance", "exhilarating", "melancholy", "serendipity", "quintessential", "idiosyncrasy",
#     "acquiesce", "benevolent", "cacophony", "deleterious", "ephemeral", "facetious", "gregarious", "hierarchy", "incessant", "juxtapose",
#     "kaleidoscope", "labyrinth", "magnanimous", "nonchalant", "obfuscate", "paradigm", "quixotic", "resilient", "surreptitious", "ubiquitous"
# ]


HARD_WORDS = [
    "alleviate", "ambiguous", "anecdote", "analyze", "antagonize", "apathy", "arbitrary", "assess", "assert", "assimilate",
    "audacious", "augment", "authentic", "bias", "brevity", "bureaucratic", "candid", "coherent", "collaborate", "comprehensive",
    "concede", "concurrent", "condone", "consequently", "contradict", "corroborate", "credible", "critique", "culminate", "cynical",
    "debate", "deduce", "deficit", "delineate", "denounce", "depict", "deteriorate", "deviate", "discrepancy", "disseminate",
    "distort", "diverse", "dominate", "elaborate", "elicit", "empirical", "endeavor", "enhance", "eradicate", "evaluate",
    "exacerbate", "exemplify", "exhaustive", "feasible", "fluctuate", "formidable", "frivolous", "fundamental", "hierarchy", "hypothesis",
    "illustrate", "immense", "imminent", "impartial", "implement", "imply", "incentive", "incline", "inconsistent", "indifferent",
    "inevitable", "infer", "integral", "intensify", "intervene", "intuitive", "intricate", "invariably", "ironic", "justify",
    "lucrative", "manipulate", "meticulous", "negligible", "notion", "obstacle", "offset", "paradox", "perceive", "pertinent",
    "plausible", "predominant", "prevalent", "profound", "prohibit", "propensity", "proponent", "rational", "reciprocal", "redundant",
    "relevant", "resilient", "restrain", "retrospect", "reveal", "rigorous", "scrutiny", "subsequent", "substantial", "succinct",
    "superficial", "sustain", "tangible", "tentative", "theoretical", "undermine", "unprecedented", "validate", "viable", "volatile",
    "abate", "aberration", "abhor", "abstain", "abstract", "abundant", "acclaim", "acumen", "adept", "adverse",
    "advocate", "aesthetic", "affluent", "agile", "alienate", "allocate", "ambivalent", "anachronistic", "analyze", "animosity",
    "anomaly", "anonymous", "antagonist", "anticipate", "antipathy", "apprehensive", "arbitrary", "arduous", "articulate", "assert",
    "assess", "assiduous", "assimilate", "astute", "atrocity", "attain", "attribute", "audacious", "augment", "austere",
    "authentic", "autonomous", "aversion", "belligerent", "benevolent", "biased", "bolster", "brevity", "candid", "capricious",
    "catalyst", "caustic", "censure", "circuitous", "circumvent", "clandestine", "coerce", "cognitive", "coherent", "cohesive",
    "collaborate", "colloquial", "commence", "compelling", "complacent", "comprehensive", "conceive", "concise", "concurrent", "condone",
    "conform", "congregate", "consensus", "consequently", "consolidate", "conspicuous", "constrain", "constructive", "contemplate", "contentious",
    "contingent", "contradict", "contribute", "conundrum", "conventional", "converge", "convey", "conviction", "corroborate", "counteract",
    "credibility", "culminate", "cynical", "debate", "decipher", "deficiency", "deficit", "delineate", "demise", "denounce",
    "depict", "derive", "detrimental", "deviation", "dichotomy", "diffuse", "diminish", "discern", "discrepancy", "discriminate",
    "disdain", "disparage", "disparate", "dispel", "disseminate", "dissipate", "distort", "divergent", "divulge", "dogmatic",
    "dominate", "dynamic", "eclectic", "elaborate", "elicit", "elude", "emulate", "endeavor", "enhance", "enigma",
    "ephemeral", "equitable", "erratic", "esoteric", "establish", "evade", "evaluate", "evoke", "exacerbate", "exemplary",
    "exhaustive", "exonerate", "expedite", "exploit", "facilitate", "feasible", "fluctuate", "forage", "formidable", "fortify",
    "foster", "frivolous", "fundamental", "galvanize", "garner", "gregarious", "hamper", "hierarchy", "hypothetical", "idiosyncratic",
    "illuminate", "illustrate", "immerse", "immense", "imminent", "impartial", "implement", "implicit", "incentive", "incessant",
    "inclination", "incompetent", "inconsistent", "indifferent", "indigenous", "induce", "inevitable", "infer", "inherent", "innovate",
    "insatiable", "insight", "insinuate", "integral", "integrate", "intensify", "intermittent", "intricate", "inundate", "invalidate",
    "invoke", "ironic", "jargon", "juxtapose", "keen", "latent", "laud", "legitimate", "lethargic", "lucid",
    "lucrative", "malicious", "manifest", "manipulate", "marginal", "melancholy", "meticulous", "mitigate", "mundane", "negligent",
    "notion", "novel", "nuance", "oblivious", "obsolete", "obstinate", "obstruct", "ominous", "onerous", "opaque",
    "oppress", "optimistic", "ornate", "paradox", "paramount", "partisan", "patronize", "perception", "perennial", "peril",
    "permeate", "perpetuate", "pervasive", "plausible", "ponder", "potent", "pragmatic", "precedent", "predominant", "preliminary",
    "prevalent", "profound", "prohibit", "propensity", "proponent", "provisional", "prudent", "qualitative", "quantitative", "quintessential",
    "ramification", "rationale", "rebuke", "reciprocal", "refine", "reiterate", "relinquish", "relevant", "remorse", "renowned",
    "repercussion", "resilient", "restrain", "retaliate", "revere", "rigorous", "rudimentary", "scrutinize", "secular", "simultaneous",
    "skeptical", "solicit", "speculate", "spontaneous", "sporadic", "staunch", "stringent", "subsequent", "substantiate", "subtle",
    "succinct", "superficial", "suppress", "surpass", "sustain", "tangible", "tentative", "terse", "theoretical", "transcend",
    "transparent", "turbulent", "ubiquitous", "unprecedented", "validate", "vehement", "venerate", "veracity", "vicarious", "vigilant",
    "vindicate", "volatile", "warrant", "whimsical", "widespread", "witty", "yield", "zealous"




]


CHALLENGING_WORDS = [
    "onomatopoeia", "pseudopseudohypoparathyroidism", "floccinaucinihilipilification", "antidisestablishmentarianism", "pneumonoultramicroscopicsilicovolcanoconiosis",
    "hippopotomonstrosesquippedaliophobia", "supercalifragilisticexpialidocious", "honorificabilitudinitatibus", "sesquipedalian", "dichlorodifluoromethane",
    "incomprehensibilities", "subdermatoglyphic", "unimaginatively", "uncopyrightable", "dermatoglyphics"
]

SENTENCES = [
    "The sun shines bright today",
    "What time does the store open",
    "She loves to read mysteries",
    "I drink coffee and like tea",
    "They walked to the grocery store",
    "The playful cat sat on window",
    "Can you help me now",
    "He finished homework before dinner",
    "The flowers bloom in the spring",
    "We will go to the beach",
    "The forecast predicts rain tomorrow",
    "Why did she pack carefully",
    "The teacher explained the lesson well",
    "He plays guitar with great skill",
    "Although it was late it helped",
    "They discussed the best solution together",
    "The museum had rare artifacts displayed",
    "She rescheduled her appointment for family",
    "Did you see students present findings",
    "After a long day he relaxed",
    "I love rain on the roof",
    "The movie was thrilling and fun",
    "He bought a new bicycle",
    "The teacher gave us extra time",
    "Why does she bring book",
    "The dog loves to chase squirrels",
    "They enjoyed a quiet evening together",
    "The chef prepared gourmet meals today",
    "We explored the forest and found",
    "He wrote a letter to friend",
    "She plays violin in orchestra",
    "The kids are excited for holiday",
    "He enjoys long runs in mornings",
    "The sunset painted the sky beautifully",
    "She found a wallet on ground",
    "The teacher assigned a challenging project",
    "Are they planning a surprise party",
    "He loves to learn about cultures",
    "The storm caused power outages everywhere",
    "She painted her room bright blue",
    "The bakery sells fresh pastries daily",
    "We had a great time at park",
    "What did the students do today",
    "He often volunteers at shelters",
    "The conference will be in hotel",
    "She knitted a scarf for grandmother",
    "The cat curled up for nap",
    "Why does he prefer novels over movies",
    "The athlete trained hard for competition",
    "She enjoys hiking in the mountains",
    "The team worked together to complete project",
    "We went camping in the woods",
    "The singer captivated the audience completely",
    "He enjoys collecting stamps from countries",
    "The children made colorful drawings today",
    "She often swims in the local pool",
    "The park has a beautiful pond",
    "Did he participate in charity run",
    "The weather is perfect for beach",
    "She enjoys writing poetry in evenings",
    "The festival featured music and food",
    "What do you love about skateboarding",
    "They built a snowman in winter",
    "The classroom was decorated with art",
    "She made a scrapbook of memories",
    "The kitten played with ball of yarn",
    "He enjoys exploring places on bike",
    "The teacher encouraged questions from students",
    "They discovered a restaurant downtown",
    "The theater is showing new films",
    "Did she write story for class",
    "He enjoys fishing at nearby lake",
    "The parade was filled with floats",
    "Why did she organize study group",
    "The beach was crowded with tourists",
    "He bought a gift for friend",
    "The team celebrated their big win",
    "She baked cookies for neighbors today",
    "The orchestra played a beautiful piece",
    "He enjoys gardening and growing vegetables",
    "The hotel had a stunning view",
    "Did she compete in dance contest",
    "The children had fun at zoo",
    "He loves taking photographs of nature",
    "The coach motivated players to win",
    "They visited a historical site together",
    "Why does she love documentaries about animals",
    "The city lights sparkled at night",
    "He is learning how to play chess",
    "The flowers smelled sweet in spring",
    "What did she take for relaxation",
    "The recipe calls for fresh herbs",
    "He enjoys writing songs in free time",
    "The beach was perfect for picnic",
    "She painted her nails bright red",
    "The dog chased the ball eagerly",
    "He enjoys reading about science topics",
    "The family took a road trip",
    "She organized her closet very well",
    "The kids played games at party",
    "He loves roller coasters very much",
    "The librarian recommended a great book",
    "Did she practice speech in front",
    "The sunset was breathtaking and beautiful",
    "He enjoys watching sports on TV",
    "The restaurant had a cozy vibe",
    "She enjoys visiting art galleries often",
    "The chef created a unique dish",
    "He loves exploring hiking trails nearby",
    "The children made bracelets together today",
    "What did she take to relax",
    "The fireworks lit the night sky",
    "He enjoys playing chess with grandfather",
    "The kids loved the puppet show",
    "Did she bake cake for wedding",
    "The musician played a beautiful tune",
    "He enjoys watching space documentaries",
    "The garden was filled with flowers",
    "She loves learning languages very much",
    "The cat jumped on the table",
    "He enjoys volunteering at community center",
    "The mountain view was breathtaking today",
    "She is planning a trip to Italy",
    "The bookstore has many good novels",
    "He loves playing board games with family",
    "The students organized a fundraiser today",
    "She enjoys meditating in the morning",
    "The concert was a big success",
    "He built a treehouse in backyard",
    "The beach was the best picnic spot",
    "She took a class to improve",
    "The children played in sandbox at park",
    "He enjoys traveling to new countries",
    "The art exhibit featured local artists",
    "She made a presentation for project",
    "The garden was lush and green",
    "He enjoys hiking in fall weather",
    "The concert hall had great acoustics",
    "She loves to try new recipes",
    "The students went on a field trip",
    "He enjoys listening to audiobooks daily",
    "The flowers were in bloom in spring",
    "She took her dog for walk",
    "The teacher praised students for hard work",
    "He enjoys writing letters to pen pal",
    "The wildlife reserve is home to many animals",
    "Did she complete marathon for first time",
    "The bakery was known for pastries",
    "He plays soccer every Saturday morning",
    "The movie was both fun and interesting",
    "She spent the afternoon reading by pool",
    "The chef prepared gourmet meal for guests",
    "He enjoys fishing in river during summer",
    "The hotel offered a variety of amenities",
    "She loves exploring new hiking trails",
    "The children had fun at birthday party",
    "He enjoys listening to classical music",
    "The city has many parks to enjoy",
    "Did she decorate room with posters",
    "The team trained hard for upcoming match",
    "They discovered a secret garden behind house",
    "The book I borrowed is interesting",
    "He forgot to bring umbrella when rained",
    "We celebrated our anniversary with dinner",
]

PRONUNCIATION_SENTENCES = [
    "The quick brown fox jumps over the lazy dog.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "She sells seashells by the seashore.",
    "Peter Piper picked a peck of pickled peppers.",
    "I scream, you scream, we all scream for ice cream.",
    "The rain in Spain stays mainly in the plain.",
    "To be or not to be, that is the question.",
    "A journey of a thousand miles begins with a single step.",
    "Actions speak louder than words.",
    "All that glitters is not gold.",
]


PRONUNCIATION_SENTENCES = [
   
    "She sings beautifully every day",
    "He enjoys reading interesting books",
    "The sun shines brightly today",
    "I want to travel abroad",
    "The students answered all questions",
    "Can you help me please",
    "He quickly finished his homework",
    "They visited the art gallery",
    "This cake tastes really delicious",
    "She often practices yoga weekly",
    "He plays the guitar perfectly",
    "The weather is quite pleasant",
    "They always eat healthy food",
    "I enjoy learning new languages",
    "She runs fast in marathons",
    "The movie was really exciting",
    "They like watching documentaries together",
    "He speaks three languages fluently",
    "The dog barked loudly at night",
    "I bought fresh fruits today",
    "She loves dancing to music",
    "He drew a beautiful picture",
    "The children played outside happily",
    "We should recycle our waste",
    "She studied for her exams",
    "He enjoys cooking new recipes",
    "The flowers bloomed in spring",
    "They traveled to Japan last year",
    "She wrote an interesting story",
    "The train arrives every hour",
    "He is learning to swim",
    "The cake needs more sugar",
    "She likes to paint landscapes",
    "They attend classes every Saturday",
    "He works at a software company",
    "The restaurant serves Italian cuisine",
    "She visited her grandparents last weekend",
    "They went hiking in nature",
    "He collects stamps from countries",
    "She is reading a novel now",
    "The teacher explained the lesson",
    "I prefer tea over coffee",
    "The library has many resources",
    "He often plays chess with friends",
    "She enjoys gardening in her backyard",
    "They are watching a play tonight",
    "He bought a new bicycle",
    "The kids are playing soccer",
    "She finished her project early",
    "They love going to concerts",
    "He took beautiful photographs yesterday",
    "The presentation was quite informative",
    "She is training for a marathon",
    "The cake looks very tempting",
    "He won the competition last year",
    "They are learning about ecosystems",
    "She joined a book club recently",
    "He plays video games every weekend",
    "The art exhibition was amazing",
    "She teaches math at school",
    "He listens to classical music",
    "They like exploring new places",
    "She enjoys writing in her journal",
    "He participated in a workshop",
    "The team won the championship",
    "She visited several historical sites",
    "They went camping in the mountains",
    "He loves photography and nature",
    "She sings in the choir",
    "They cooked a special dinner",
    "He runs every morning before work",
    "The coffee shop has free Wi-Fi",
    "She shared her ideas confidently",
    "They bought tickets for the show",
    "He enjoys fishing by the lake",
    "The documentary was very educational",
    "She practices speaking every day",
    "They organized a charity event",
    "He loves hiking in the mountains",
    "The museum has interesting exhibits",
    "She is learning to play piano",
    "They went for a long walk",
    "He enjoys cycling on weekends",
    "The cake recipe was easy",
    "She likes trying new cuisines",
    "They went to the beach today",
    "He volunteered at a shelter",
    "She enjoys attending live performances",
    "The garden is blooming beautifully",
    "He wrote a heartfelt letter",
    "They discussed various topics openly",
    "She paints with vibrant colors",
    "He shares interesting articles online",
    "The music festival was fun",
    "She listens to podcasts regularly",
    "They like to have picnics",
    "He enjoys studying history deeply",
    "The chocolate tastes very rich",
    "She loves spending time outdoors",
    "They enjoyed the fireworks display",
    "He has a unique perspective",
    "She shares her thoughts honestly",
    "The puppy is very playful",
    "He cooked dinner for everyone",
    "They are planning a trip soon",
    "She loves to explore nature",
    "He attended a motivational seminar",
    "The soup smells incredibly delicious",
    "She enjoys solving puzzles often",
    "They play board games together",
    "He has many interesting hobbies",
    "She is a talented artist",
    "They learned a new skill",
    "He is studying environmental science",
    "She enjoys learning about cultures",
    "The landscape was breathtakingly beautiful",
    "They traveled across the country",
    "He likes to help others",
    "She loves to write poetry",
    "They are working on a project",
    "He enjoys visiting new cities",
    "She is a great storyteller",
    "They practice together every week",
    "He bought new hiking boots",
    "The sunset was absolutely stunning",
    "She enjoys attending cooking classes",
    "They have a fun tradition",
    "He likes watching documentaries",
    "The cake was a big hit",
    "She enjoys spending time alone",
    "They celebrated his birthday yesterday",
    "He enjoys drawing in his spare time",
    "The show received rave reviews",
    "She loves giving back to community",
    "They visited a famous landmark",
    "He collects vintage postcards passionately",
    "She enjoys quiet mornings with coffee",
    "They always choose to walk",
    "He loves to read fantasy novels",
    "The garden was filled with flowers",
    "She shares her music with friends",
    "They often volunteer for local charities",
    "He enjoys experimenting with flavors",
    "The park is a great escape",
    "She likes to meditate in silence",
    "They discuss current events often",
    "He has an extensive library",
    "The team worked well together",
    "She is learning about nutrition",
    "They enjoyed a relaxing weekend",
    "He likes to play chess",
    "The ocean waves sound soothing",
    "She enjoys writing short stories",
    "They participate in community events",
    "He loves to make others laugh",
    "The flowers smell wonderful outside",
    "She practices yoga for relaxation",
    "They enjoy going to the movies",
    "He writes songs in his free time",
    "The coffee shop has great ambiance",
    "She likes to collect antiques",
    "They spend weekends exploring together",
    "He enjoys making new friends",
    "The sunset colors were beautiful",
    "She loves to learn new skills",
    "They like to watch wildlife",
    "He always carries a camera",
    "The snow was falling softly",
    "She enjoys giving compliments sincerely",
    "They went on a road trip",
    "He shares his travel stories",
    "The food was very spicy",
    "She loves to help people",
    "They discovered a hidden beach",
    "He enjoys watching sports on TV",
    "The garden attracts many butterflies",
    "She takes beautiful photographs regularly",
    "They are planning a surprise party",
    "He loves attending music festivals",
    "The cake decoration was creative",
    "She enjoys cooking for friends",
    "They watched a thrilling movie",
    "He likes reading historical novels",
    "The sky is a beautiful blue",
    "She enjoys exploring new cuisines",
    "They volunteered at the animal shelter",
    "He loves hiking in the forest",
    "The painting was quite impressive",
    "She likes to make jewelry",
    "They went on a scenic drive",
    "He enjoys helping out at school",
    "The landscape was incredibly scenic",
    "She likes visiting art galleries",
    "They had a fantastic adventure",
    "He loves studying marine biology",
    "The picnic was a lot of fun",
    "She enjoys playing card games",
    "They participated in a fun run",
    "He likes to listen to music",
    "The weather was perfect for hiking",
    "She enjoys working with children",
    "They visited a famous museum",
    "He loves to ride bicycles",
    "The city has beautiful architecture",
    "She enjoys reading about history",
    "They went to a concert last week",
    "He likes to take long walks",
    "The chocolate cake was delicious",
    "She enjoys visiting local markets",
    "They celebrated their anniversary together",
    "He loves to swim in the ocean",
    "The park was filled with laughter",
    "She enjoys sharing her experiences",
    "They have a strong friendship",
    "He is passionate about photography",
    "The mountains are breathtakingly beautiful",
    "She loves to explore the forest",
    "They enjoy spending time at home",
    "He likes to watch documentaries",
    "The beach was crowded today",
    "She enjoys learning about science",
    "They went to a food festival",
    "He loves playing video games",
    "The art exhibit was inspiring",
    "She enjoys helping others succeed",
    "They often attend cultural events",
    "He likes to write in journals",
    "The garden is full of colors",
    "She loves to bake pastries",
    "They had a wonderful experience",
    "He enjoys outdoor activities often",
    "The forest is very peaceful",
    "She loves to listen to jazz",
    "They frequently travel during summer",
    "He enjoys exploring local history",
    "The festival attracted many visitors",
    "She likes watching foreign films",
    "They participated in a charity run",
    "He enjoys playing with his dog",
    "The night sky is so clear",
   

]




def get_random_word(difficulty):
    if difficulty == "simple":
        return random.choice(SIMPLE_WORDS)
        # return random.choice(["house",'tree','cat','dog'])
    elif difficulty == "medium":
        return random.choice(MEDIUM_WORDS)
    elif difficulty == "hard":
        return random.choice(HARD_WORDS)
    elif difficulty == "challenging":
        return random.choice(CHALLENGING_WORDS)
    elif difficulty == "sentence":
        return random.choice(SENTENCES)
    else:
        raise ValueError("Invalid difficulty level")

def get_all_words(difficulty):
    if difficulty == "simple":
        return SIMPLE_WORDS
        # return ["house",'tree','cat','dog']
    elif difficulty == "medium":
        return MEDIUM_WORDS
    elif difficulty == "hard":
        return HARD_WORDS
    elif difficulty == "challenging":
        return CHALLENGING_WORDS
    elif difficulty == "sentence":
        return SENTENCES
    else:
        raise ValueError("Invalid difficulty level")

def get_random_pronunciation_sentence():
    return random.choice(PRONUNCIATION_SENTENCES)

def get_all_pronunciation_sentences():
    return PRONUNCIATION_SENTENCES
